/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatSessionsRouteImport } from './routes/_chat.sessions'
import { Route as ChatGithubRouteImport } from './routes/_chat.github'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatReviewProjectIdRouteImport } from './routes/_chat.review.$projectId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSessionsRoute = ChatSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ChatRoute,
} as any)
const ChatGithubRoute = ChatGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatReviewProjectIdRoute = ChatReviewProjectIdRouteImport.update({
  id: '/review/$projectId',
  path: '/review/$projectId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/github': typeof ChatGithubRoute
  '/sessions': typeof ChatSessionsRoute
  '/settings': typeof ChatSettingsRoute
  '/review/$projectId': typeof ChatReviewProjectIdRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/github': typeof ChatGithubRoute
  '/sessions': typeof ChatSessionsRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/review/$projectId': typeof ChatReviewProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/github': typeof ChatGithubRoute
  '/_chat/sessions': typeof ChatSessionsRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/review/$projectId': typeof ChatReviewProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/github'
    | '/sessions'
    | '/settings'
    | '/review/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/github'
    | '/sessions'
    | '/settings'
    | '/'
    | '/review/$projectId'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/github'
    | '/_chat/sessions'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/review/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/sessions': {
      id: '/_chat/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof ChatSessionsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/github': {
      id: '/_chat/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof ChatGithubRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/review/$projectId': {
      id: '/_chat/review/$projectId'
      path: '/review/$projectId'
      fullPath: '/review/$projectId'
      preLoaderRoute: typeof ChatReviewProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatGithubRoute: typeof ChatGithubRoute
  ChatSessionsRoute: typeof ChatSessionsRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatReviewProjectIdRoute: typeof ChatReviewProjectIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatGithubRoute: ChatGithubRoute,
  ChatSessionsRoute: ChatSessionsRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatReviewProjectIdRoute: ChatReviewProjectIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
